name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rudo
            asset_name: rudo-$tag-linux-amd64
          - os: macos-latest
            artifact_name: rudo
            asset_name: rudo-$tag-macos-amd64

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --locked &&  tar -czvf rudo.tar.gz target/release/rudo
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}.tar.gz
        asset_name: ${{ matrix.asset_name }}.tar.gz
        tag: ${{ github.ref }}
